services:
  django:
    build:
      context: ./backend/graphql-server
    volumes:
      - ./backend/graphql-server:/app
    environment:
      - DATABASE_URL=bolt://neo4j:password@neo4j:7687
    ports:
      - "8000:8000"
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol