services:
  django:
    build:
      context: ./backend/graphql-server
    volumes:
      - ./backend/graphql-server:/app
    environment:
      - DATABASE_URL=bolt://neo4j:password@neo4j:7687
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgis
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - postgis

  react-app-dev:
    build:
      context: ./frontend/react-app
    command: npm run dev
    ports:
      - "5173:5173"  # Expose React dev server (Vite) on port 3000
    environment:  
      - VITE_REACT_APP_BACKEND_URL=http://localhost:8000/postgis/
    depends_on:
      - django  # Optional: If your React app depends on the backend being available
    volumes:
      - ./frontend/react-app:/app  # Optional: If you want to live-edit the app

  react-app-prod:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"  # Map port 80 in the container to port 3000 on the host
    environment:  
      - VITE_REACT_APP_BACKEND_URL=http://django:8000
    depends_on:
      - django  # Optional: If your React app depends on the backend being available
    volumes:
      - ./frontend/react-app:/app  # Optional: If you want to live-edit the app
    profiles:
      - production  # This service will only run when 'production' profile is used

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol

  postgis:
    image: postgis/postgis:15-3.4
    container_name: postgis_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: