services:
  django:
    build:
      context: ./django
    volumes:
      - ./django:/app
    environment:
      - DATABASE_URL=bolt://neo4j:password@neo4j:7687
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgis
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - postgis

  react-app-dev:
    build:
      context: ./react-app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:  
      - VITE_REACT_APP_BACKEND_URL=http://localhost:8000/postgis/
    depends_on:
      - django
    volumes: # live edit
      - ./react-app:/app
      - /app/node_modules

  react-app-prod:
    build:
      context: ./react-app
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:  
      - VITE_REACT_APP_BACKEND_URL=http://django:8000
    depends_on:
      - django
    volumes:
      - ./react-app:/app
    profiles:
      - production

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"

  postgis:
    image: ghcr.io/baosystems/postgis:15-3.4
    platform: linux/arm64
    container_name: postgis_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: