services:
  django:
    build:
      context: ./backend/graphql-server
    volumes:
      - ./backend/graphql-server:/app
    environment:
      - DATABASE_URL=bolt://neo4j:password@neo4j:7687
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgis
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - postgis

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol

  postgis:
    image: postgis/postgis:15-3.4
    container_name: postgis_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data: