# Generated by Django 4.2.16 on 2026-03-21 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postgis_app', '0002_route_trail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('direction', models.CharField(choices=[('F', 'Forward'), ('R', 'Reverse')], max_length=1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='postgis_app.route')),
            ],
        ),
    ]
