# Generated by Django 4.2.16 on 2026-04-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgis_app', '0003_routerun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrailSegment',
            new_name='Line',
        ),
        migrations.RemoveField(
            model_name='routerun',
            name='route',
        ),
        migrations.DeleteModel(
            name='Trail',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='RouteRun',
        ),
    ]
