# Generated by Django 4.2.16 on 2026-03-28 19:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField()),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('raw', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation', models.FloatField(null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='ingestion_app.activity')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['activity', 'sequence'], name='ingestion_a_activit_c603b9_idx')],
            },
        ),
    ]
