# Generated by Django 4.2.16 on 2026-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityPoint',
        ),
    ]
